#Archivos *_test.cpp

SOURCES += \
    $$PWD/Action/Action_test.cpp \
    $$PWD/Action/ActionFactory_test.cpp \
    $$PWD/Action/ActionFactoryES_test.cpp \
    $$PWD/Action/ActionFactoryIAS_test.cpp \
    $$PWD/Action/ActionFactoryOBC_test.cpp \
    $$PWD/Action/ActionManager_test.cpp \
    $$PWD/Action/ActionsQueue_test.cpp \
    $$PWD/Action/CaptureReqAction_test.cpp \
    $$PWD/Action/CatalogReqAction_test.cpp \
    $$PWD/Action/CatalogResAction_test.cpp \
    $$PWD/Action/CropReqAction_test.cpp \
    $$PWD/Action/DeleteReqAction_test.cpp \
    $$PWD/Action/ImageHQReqAction_test.cpp \
    $$PWD/Action/ImageHQResAction_test.cpp \
    $$PWD/Action/ImageLQReqAction_test.cpp \
    $$PWD/Action/ImageLQResAction_test.cpp \
    $$PWD/Action/KeepaliveReqAction_test.cpp \
    $$PWD/Action/KeepaliveResAction_test.cpp \
    $$PWD/Action/LedIASGetReqAction_test.cpp \
    $$PWD/Action/LedIASGetResAction_test.cpp \
    $$PWD/Action/LedIASSetReqAction_test.cpp \
    $$PWD/Action/LedOBCGetReqAction_test.cpp \
    $$PWD/Action/LedOBCSetReqAction_test.cpp \
    $$PWD/Command/CaptureCommandReq_test.cpp \
    $$PWD/Command/CatalogCommandReq_test.cpp \
    $$PWD/Command/CatalogCommandRes_test.cpp \
    $$PWD/Command/CropCommandReq_test.cpp \
    $$PWD/Command/Command_test.cpp \
    $$PWD/Command/DeleteCommandReq_test.cpp \
    $$PWD/Command/ImageHQCommandReq_test.cpp \
    $$PWD/Command/ImageHQCommandRes_test.cpp \
    $$PWD/Command/ImageLQCommandReq_test.cpp \
    $$PWD/Command/ImageLQCommandRes_test.cpp \
    $$PWD/Command/KeepaliveCommandReq_test.cpp \
    $$PWD/Command/KeepaliveCommandRes_test.cpp \
    $$PWD/Command/LedIASGetCommandReq_test.cpp \
    $$PWD/Command/LedIASGetCommandRes_test.cpp \
    $$PWD/Command/LedIASSetCommandReq_test.cpp \
    $$PWD/Command/LedOBCGetCommandReq_test.cpp \
    $$PWD/Command/LedOBCGetCommandRes_test.cpp \
    $$PWD/Command/LedOBCSetCommandReq_test.cpp \
    $$PWD/Command/TransmissionQueue_test.cpp \
    $$PWD/Computer/Computer_test.cpp \
    $$PWD/Computer/EarthStation_test.cpp \
    $$PWD/Computer/ImageAcquisitionSystem_test.cpp \
    $$PWD/Computer/OnBoardComputer_test.cpp \
    $$PWD/Error/ErrorManager_test.cpp \
    $$PWD/Image/CameraManager_test.cpp \
    $$PWD/Image/ImageDataBase_test.cpp \
    $$PWD/Image/ImageEditor_test.cpp \
    $$PWD/Image/ImageManager_test.cpp \
    $$PWD/Image/ImageProperties_test.cpp \
    $$PWD/Protocol/CommManager_test.cpp \
    $$PWD/Protocol/PacketBuilder_test.cpp \
    $$PWD/Protocol/PacketReader_test.cpp \
    $$PWD/Protocol/PacketValidator_test.cpp \
    $$PWD/Protocol/SerialPortManager_test.cpp \
    $$PWD/Screen/AbstractScreenViewModel_test.cpp \
    $$PWD/Screen/MainScreenViewModel_test.cpp \
    $$PWD/Screen/ScreenProperties_test.cpp \
    $$PWD/Screen/Components/ButtonViewModel_test.cpp \
    $$PWD/Screen/Components/ImagePropertiesViewModel_test.cpp \
    $$PWD/Screen/Components/InfoTextViewModel_test.cpp \
    $$PWD/Screen/Components/TextFieldViewModel_test.cpp \
    $$PWD/Utils/Files_test.cpp \
    $$PWD/Utils/ImageFileInfo_test.cpp \
    $$PWD/Utils/Operators_test.cpp \
    $$PWD/CommLinkMonitor_test.cpp \
    $$PWD/ViewModel_test.cpp \
    $$PWD/ViewModelManager_test.cpp


